version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: hospital-pdf-postgres
    restart: always
    environment:
      POSTGRES_USER: aman
      POSTGRES_PASSWORD: aman123
      POSTGRES_DB: hospitaldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
